- README.md
Adding at the suggestion of @alallema
> Add meilisearch-python-async

- README.md
Adds meilisearch-fastapi to community integrations.
> Add meilisearch-fastapi

- README.md
Add community elixir wrapper for Meilisearch :D
> Add community elixir wrapper for Meilisearch

- README.md
> Add GH Action created by @moy2010

- README.md
On request by https://github.com/dwarfhq/laravel-meilitools/issues/2
> Added Laravel MeiliTools to community tools list

- README.md
None
- Adds the [BandsNear](https://www.bandsnear.com/) platform in the `Awesome use of Meilisearch` section.
> readme: add BandsNear platform

- README.md
[Meiliadmin](https://github.com/kaermorchen/meiliadmin) - Dashboard for Meilisearch
> Add Meiliadmin

- README.md
Hope all is well; a somewhat recent, beginner-friendly Laravel 9/Scout tutorial. Cheers.
- Add new tutorial to Community Guides
- [x ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
> Add Laravel 9/Scout tutorial to Community Guides

- README.md
Fixes #25
- Updates the demo with Matching Strategy.
> Update: Added Matching strategy demo in the README.md

- README.md
- Nothing broken here. Just added [Nest-MeiliSearch](https://www.npmjs.com/package/nest-meilisearch)  to the list of community integrations
> Added Nest-MeiliSearch to community integrations

- README.md
- Fixed the link to the community, [from Slack to Discord](https://blog.meilisearch.com/from-slack-to-discord-our-migration/).
> Update link to community

- README.md
This is an exciting package that mixes docscraper + laravel. And it is very popular :)
> Add laravel-site-search to the list

- README.md
- Adds Meilisearch TUI to the community tools
> Add meilisearch-tui

- README.md
none
- This change fixes the outdated link to the Postman collection.
> fix: update link to postman collection

- README.md
None
[Testcontainers Meilisearch](https://testcontainers.com/modules/meilisearch/) is a community module to help with integration testing in the JVM environment.
> Add Testcontainers Meilisearch to community tools

- README.md
- Adds `pytest-meilisearch`. This provides helpers/fixtures for testing integrating Meilisearch in Python projects
> Add pytest-meilisearch

- README.md
Add https://github.com/CodyTseng/meilisearch-helper
meilisearch-helper is a helper library for meilisearch-js that provides convenient utility methods to simplify common operations and enhance your Meilisearch experience. Now it can help generate `filter` and `sort`.
> Add meilisearch-helper

- README.md
Please say hello to [Meiliweb](https://meiliweb.pages.dev/), a brand new UI for managing Meilisearch instances! 👋 🔍
> Feat: Suggest Meiliweb

- README.md
* [meilisearch-filters](https://www.npmjs.com/package/meilisearch-filters) - A fluent interface to build Meilisearch filters (Javascript / Typescript)
* [bentools/meilisearch-filters](https://packagist.org/packages/bentools/meilisearch-filters) -  A fluent interface to build Meilisearch filters (PHP)
> Feat: Suggest `meilisearch-filters` and `meilisearch-filters-php`

- README.md
> Update README.md with Coolify Deploy

- README.md
Adding django-meili to the list of "Community Tools"
https://github.com/ikollipara/django-meili
> Add django-meili

- README.md
- Updated outdated links to official guides
> Updated official links and guides
